// Mocks generated by Mockito 5.4.4 from annotations
// in buruan_sae/test/features/auth/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:buruan_sae/features/auth/data/providers/auth_provider.dart'
    as _i3;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthState_1 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStateNotifier extends _i1.Mock implements _i3.AuthStateNotifier {
  MockAuthStateNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeNotifierProviderRef<_i3.AuthState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<_i3.AuthState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<_i3.AuthState>);

  @override
  _i3.AuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAuthState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AuthState);

  @override
  set state(_i3.AuthState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AuthState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeAuthState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.AuthState);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> register({
    required String? nik,
    required String? namaLengkap,
    required String? nomorWa,
    String? email = r'',
    required String? password,
    required String? peran,
    bool? consentDataPribadi = true,
    bool? consentPublikasiData = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #nik: nik,
            #namaLengkap: namaLengkap,
            #nomorWa: nomorWa,
            #email: email,
            #password: password,
            #peran: peran,
            #consentDataPribadi: consentDataPribadi,
            #consentPublikasiData: consentPublikasiData,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> kirimOtp(String? nomorWa) => (super.noSuchMethod(
        Invocation.method(
          #kirimOtp,
          [nomorWa],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> verifikasiOtp({
    required String? nomorWa,
    required String? kodeOtp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifikasiOtp,
          [],
          {
            #nomorWa: nomorWa,
            #kodeOtp: kodeOtp,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithOtp(
    String? nomorWa,
    String? kodeOtp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithOtp,
          [
            nomorWa,
            kodeOtp,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithPassword({
    required String? identifier,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithPassword,
          [],
          {
            #identifier: identifier,
            #password: password,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i3.AuthState?,
      _i3.AuthState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.AuthState? previous,
    _i3.AuthState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
